spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:tcp://localhost/~/Projects/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시점에 테이블을 다 지우고 Entity를 이용해서 다시 생성한다.
    properties:
      hibernate:
        # show_sql: true # 로그를 systemout으로 보여준다.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger로 보여준다.
    org.hibernate.type: trace # 쿼리의 파라미터를 ? 가 아니라 실제 데이터 값으로 볼 수 있게 해준다.

---
spring:
  config:
    activate:
      on-profile: default